### ISSUE TITLE
incomplete backup

### ISSUE THREAD

**Issue by cop98** [internxt/drive-desktop-macos#59]
By starting the backup through the appropriate function, it is performed incompletely.
In fact, for a 120 gb folder, only 70 gb is occupied in the destination and in fact files are missing.

In the interface, the backup appears to be completed correctly. 
Each time I restart the backup the destination folder increases slightly, but it is never complete

**Comment by PixoDev** [comment]
Hey there,

Please only use this channel to report code directly related issues, if you have any issue with the app itself and you need our assistance, reach us at hello@internxt.com please.
